### ISSUE TITLE
Security Vulnerability: Chosen-Ciphertext Attacks (all versions)

### ISSUE THREAD

**Issue by sarciszewski** [CoreProc/crypto-guard#1]
https://github.com/CoreProc/crypto-guard/blob/e1082bb98ee12f9f25cc642b5e7c468942cb263e/src/CryptoGuard.php#L16-L44

During encryption, you should be applying a MAC (e.g. `hash_hmac()` with 'sha256' as the algorithm) of the IV and ciphertext.

When you attempt to decrypt a message you should recalculate the MAC of the received IV and ciphertext, then compare the MAC you calculated with the MAC you received in [constant-time](http://php.net/hash_equals).

Encrypt then MAC. Verify then decrypt. If verification fails, abort; do not attempt decryption.

Further reading:

* http://tonyarcieri.com/all-the-crypto-code-youve-ever-written-is-probably-broken
* https://paragonie.com/blog/2015/05/using-encryption-and-authentication-correctly
* http://www.thoughtcrime.org/blog/the-cryptographic-doom-principle/

**Comment by sarciszewski** [comment]
`May 14 <--- enormous gulf of time ---> December 6`

Yeah, this isn't going to be fixed any time soon. If ever.

**Comment by Faryshta** [comment]
thats notreason to close it. when i opened the link and saw it was closed my inmediate reaction is "well at least its fixed now"

**Comment by sarciszewski** [comment]
Fair point. I've reluctantly reopened this issue full knowing that the people who maintain this likely don't care if they've given people a false sense of security.

**Comment by Faryshta** [comment]
Yup, issues are also meant for the users to know there is something that has not been fixed, specially those who find this page after a google search.

**Comment by chrisbjr** [comment]
Hi @sarciszewski sorry for the super late response - we've been meaning to fix this but never really got to it. Above is an attempt to patch the vulnerability by attaching an hmac signature to the payload and verifying it upon decryption. Thanks for pointing this out to us. Let me know if this truly patches up this issue.

**Comment by paragonie-scott** [comment]
Is the Salt included in the ciphertext? If so, it should be included in the HMAC. Letting an attacker control any of the bits without breaking the MAC is risky.

**Comment by chrisbjr** [comment]
Hi @paragonie-scott the salt is now included in the HMAC inside the latest commit. This has now been tagged as v1.0.0. Thanks to @sarciszewski for bringing this up.
